Makefile.Linux: Check for liburing submodule before building
Add a pre-build check for ${LIBURING_DIR}/src in the ${LIBURING_A}
target. If the directory is missing, print an error advising the user
to run 'git submodule init && git submodule update' and fail early.

Co-authored-by: Cursor <cursoragent@cursor.com>
Signed-off-by: Govindarajulu Varadarajan <govindarajulu.varadarajan@amd.com>

Acked-by: Gregory Williams <gregory.williams@amd.com>
(cherry picked from commit 30a8ebf9aceb2167b17589a6b0587ba44caa589a)
Signed-off-by: Govindarajulu Varadarajan <govindarajulu.varadarajan@amd.com>

diff --git a/driver/src/Makefile.Linux b/driver/src/Makefile.Linux
--- a/driver/src/Makefile.Linux
+++ b/driver/src/Makefile.Linux
@@ -32,6 +32,11 @@ LIBURING_A ?= ${LIBURING_DIR}/src/liburing.a
 all: include lib$(NAME).so lib$(NAME).a
 
 ${LIBURING_A}:
+	@if [ ! -d "${LIBURING_DIR}/src" ]; then		\
+		echo "Error: ${LIBURING_DIR}/src not found.";	\
+		echo "Run: git submodule init && git submodule update"; \
+		exit 1;						\
+	fi
 	cd ${LIBURING_DIR};				\
 	./configure --cc=${CC} --cxx=${CXX};		\
 	make -j32;					\
